### ISSUE TITLE
BUG: Login not possible after wallet change

### ISSUE THREAD

**Issue by steffenkux** [corpus-io/dm3#454]
## Conditions
Set wallet A in Metamask and log in (signature). -> works
Go to Metamask and change your wallet (to wallet B).
Refresh browser (see #453 ) -> Sign in screen is shown
Press the "Sign in" button

## Current behavior
After some seconds an attention sign is shown on the button. Nothing else happens. No error message is displayed.
![image](https://user-images.githubusercontent.com/26625404/224948568-585208aa-3cb9-4e88-b915-dcc7b9b43f22.png)

## Expected behavior
Login to the inbox of the selected wallet

**Comment by hai-ko** [comment]
I guess this is because of an unsupported old signature in the profile record on-chain.
