### ISSUE TITLE
Identify prerequisites for react component library

### ISSUE THREAD

**Issue by Bhupesh-mfsi** [corpus-io/dm3#542]
## Prerequisites

**1. APIs needed :-** 

- Edit the message.
- Delete the message.
- Reply to the message.
- Add reaction to the message.
- Send, delete & reply to the attachments (**only if there is separate API's for this**).

**2. Configuration :-**

- Provide **WalletConnect** **project ID** to use **WalletConnect** in Rainbow wallet.
- Provide **Infura** and **Alchemy** **api key** to use Ethereum node provider in Rainbow wallet.
- Provide the zip file containing all the images and icons required as shown in figma design with **svg extension**.

**3. Environment :-**

- Goerli setup.
- Staging server for web app.

**4. Questions :-**

- Which API/method is to be called to get **profile picture, email id,  github etc..** to show on user profile page? Provide the method/API for that. 
- What does that **delete button icon** do on the DM3 profile modal popup beside the DM3 name in UI. Provide the method/API needed for that.

**Comment by hai-ko** [comment]
> ## Prerequisites
> **1. APIs needed :-**
> 
> * Edit the message.

- [x] https://github.com/corpus-io/dm3/blob/89dc7cb4d90fa3e87246e0c69001976a2dc41efc/packages/lib/messaging/src/Message.ts#L176

> * Delete the message.

- [x] https://github.com/corpus-io/dm3/blob/89dc7cb4d90fa3e87246e0c69001976a2dc41efc/packages/lib/messaging/src/Message.ts#L144

> * Reply to the message.

- [x] https://github.com/corpus-io/dm3/blob/89dc7cb4d90fa3e87246e0c69001976a2dc41efc/packages/lib/messaging/src/Message.ts#L205

> * Add reaction to the message.

- [x] https://github.com/corpus-io/dm3/blob/89dc7cb4d90fa3e87246e0c69001976a2dc41efc/packages/lib/messaging/src/Message.ts#L234

> * Send, delete & reply to the attachments (**only if there is separate API's for this**).

Attachments are always part of a message. So you can only send, delete & reply to the message containing the attachment.

> 
> **2. Configuration :-**
> 
> * Provide **WalletConnect** **project ID** to use **WalletConnect** in Rainbow wallet.

- [x] I'll send you the WalletConnect projectID in slack.

> * Provide **Infura** and **Alchemy** **api key** to use Ethereum node provider in Rainbow wallet.

- [x] I'll send you the API key in slack.

> * Provide the zip file containing all the images and icons required as shown in figma design with **svg extension**.

- [ ] @steffenkux could you provide this zip file?

> 
> **3. Environment :-**
> 
> * Goerli setup.

- [ ] I'll finish this later today.

> * Staging server for web app.

- [ ] I started to write a github workflow that will publish to staging every time something is pushed to the `new-ui` branch. I'll enable this as soon as you finished creating the messenger-demo package.

> 
> **4. Questions :-**
> 
> * Which API/method is to be called to get **profile picture, email id,  github etc..** to show on user profile page? Provide the method/API for that.

This is retrieved directly from ENS and not over our API. You can use ethers to get the data (https://docs.ethers.org/v5/api/providers/provider/#Provider--ens-methods)

> * What does that **delete button icon** do on the DM3 profile modal popup beside the DM3 name in UI. Provide the method/API needed for that.

Not sure which  **delete button icon** you mean. @Bhupesh-mfsi could you send me a screenshot?

**Comment by Bhupesh-mfsi** [comment]
> > ## Prerequisites
> > **1. APIs needed :-**
> > 
> > * Edit the message.
> 
> * [x]  https://github.com/corpus-io/dm3/blob/89dc7cb4d90fa3e87246e0c69001976a2dc41efc/packages/lib/messaging/src/Message.ts#L176
> 
> > * Delete the message.
> 
> * [x]  https://github.com/corpus-io/dm3/blob/89dc7cb4d90fa3e87246e0c69001976a2dc41efc/packages/lib/messaging/src/Message.ts#L144
> 
> > * Reply to the message.
> 
> * [x]  https://github.com/corpus-io/dm3/blob/89dc7cb4d90fa3e87246e0c69001976a2dc41efc/packages/lib/messaging/src/Message.ts#L205
> 
> > * Add reaction to the message.
> 
> * [x]  https://github.com/corpus-io/dm3/blob/89dc7cb4d90fa3e87246e0c69001976a2dc41efc/packages/lib/messaging/src/Message.ts#L234
> 
> > * Send, delete & reply to the attachments (**only if there is separate API's for this**).
> 
> Attachments are always part of a message. So you can only send, delete & reply to the message containing the attachment.
> 
> > **2. Configuration :-**
> > 
> > * Provide **WalletConnect** **project ID** to use **WalletConnect** in Rainbow wallet.
> 
> * [x]  I'll send you the WalletConnect projectID in slack.
> 
> > * Provide **Infura** and **Alchemy** **api key** to use Ethereum node provider in Rainbow wallet.
> 
> * [x]  I'll send you the API key in slack.
> 
> > * Provide the zip file containing all the images and icons required as shown in figma design with **svg extension**.
> 
> * [ ]  @steffenkux could you provide this zip file?
> 
> > **3. Environment :-**
> > 
> > * Goerli setup.
> 
> * [ ]  I'll finish this later today.
> 
> > * Staging server for web app.
> 
> * [ ]  I started to write a github workflow that will publish to staging every time something is pushed to the `new-ui` branch. I'll enable this as soon as you finished creating the messenger-demo package.
> 
> > **4. Questions :-**
> > 
> > * Which API/method is to be called to get **profile picture, email id,  github etc..** to show on user profile page? Provide the method/API for that.
> 
> This is retrieved directly from ENS and not over our API. You can use ethers to get the data (https://docs.ethers.org/v5/api/providers/provider/#Provider--ens-methods)
> 
> > * What does that **delete button icon** do on the DM3 profile modal popup beside the DM3 name in UI. Provide the method/API needed for that.
> 
> Not sure which **delete button icon** you mean. @Bhupesh-mfsi could you send me a screenshot?

![DM3 profile config](https://github.com/corpus-io/dm3/assets/137804674/3a62446f-6c91-4d0e-a649-23d9e20238ff)
Please check this image , there is a **delete icon** to the right of **DM3 Name**

**Comment by hai-ko** [comment]
> > > ## Prerequisites
> > > **1. APIs needed :-**
> > > 
> > > * Edit the message.
> > 
> > 
> > 
> > * [x]   https://github.com/corpus-io/dm3/blob/89dc7cb4d90fa3e87246e0c69001976a2dc41efc/packages/lib/messaging/src/Message.ts#L176
> > 
> > > * Delete the message.
> > 
> > 
> > 
> > * [x]   https://github.com/corpus-io/dm3/blob/89dc7cb4d90fa3e87246e0c69001976a2dc41efc/packages/lib/messaging/src/Message.ts#L144
> > 
> > > * Reply to the message.
> > 
> > 
> > 
> > * [x]   https://github.com/corpus-io/dm3/blob/89dc7cb4d90fa3e87246e0c69001976a2dc41efc/packages/lib/messaging/src/Message.ts#L205
> > 
> > > * Add reaction to the message.
> > 
> > 
> > 
> > * [x]   https://github.com/corpus-io/dm3/blob/89dc7cb4d90fa3e87246e0c69001976a2dc41efc/packages/lib/messaging/src/Message.ts#L234
> > 
> > > * Send, delete & reply to the attachments (**only if there is separate API's for this**).
> > 
> > 
> > Attachments are always part of a message. So you can only send, delete & reply to the message containing the attachment.
> > > **2. Configuration :-**
> > > 
> > > * Provide **WalletConnect** **project ID** to use **WalletConnect** in Rainbow wallet.
> > 
> > 
> > 
> > * [x]   I'll send you the WalletConnect projectID in slack.
> > 
> > > * Provide **Infura** and **Alchemy** **api key** to use Ethereum node provider in Rainbow wallet.
> > 
> > 
> > 
> > * [x]   I'll send you the API key in slack.
> > 
> > > * Provide the zip file containing all the images and icons required as shown in figma design with **svg extension**.
> > 
> > 
> > 
> > * [ ]   @steffenkux could you provide this zip file?
> > 
> > > **3. Environment :-**
> > > 
> > > * Goerli setup.
> > 
> > 
> > 
> > * [ ]   I'll finish this later today.
> > 
> > > * Staging server for web app.
> > 
> > 
> > 
> > * [ ]   I started to write a github workflow that will publish to staging every time something is pushed to the `new-ui` branch. I'll enable this as soon as you finished creating the messenger-demo package.
> > 
> > > **4. Questions :-**
> > > 
> > > * Which API/method is to be called to get **profile picture, email id,  github etc..** to show on user profile page? Provide the method/API for that.
> > 
> > 
> > This is retrieved directly from ENS and not over our API. You can use ethers to get the data (https://docs.ethers.org/v5/api/providers/provider/#Provider--ens-methods)
> > > * What does that **delete button icon** do on the DM3 profile modal popup beside the DM3 name in UI. Provide the method/API needed for that.
> > 
> > 
> > Not sure which **delete button icon** you mean. @Bhupesh-mfsi could you send me a screenshot?
> 
> ![DM3 profile config](https://user-images.githubusercontent.com/137804674/255838245-3a62446f-6c91-4d0e-a649-23d9e20238ff.png) Please check this image , there is a **delete icon** to the right of **DM3 Name**

Ahh ok. This is to remove the `.user.dm3.eth` alias from the off-chain resolver. The API doesn't provide this feature yet. I'll create it and let you know as soon as I finished.
