### ISSUE TITLE
BUG: UI-testing new User Interface

### ISSUE THREAD

**Issue by steffenkux** [corpus-io/dm3#631]
## Test-Environment
tested on staging environment: http://stage.dm3.network

## Found issues:

1. Startscreen image - roundings have a white frame at high resolution (tested on MAC)
![image](https://github.com/corpus-io/dm3/assets/26625404/88cccde2-32a7-4433-9285-7b343f1806b2)

2. Add some more spacing (see figma):
![image](https://github.com/corpus-io/dm3/assets/26625404/66ba8519-951d-45c1-90aa-0330acbfbfba)

3. Sign-in fails:
![image](https://github.com/corpus-io/dm3/assets/26625404/69347d45-c3ba-4840-af19-36d2675bdff9)

**Comment by Bhupesh-mfsi** [comment]
@steffenkux 
1. I have fixed the first 2 issues.
2. The 3rd issue is from backend.
3. As per my knowledge the current staging environment you are using is not update. The new staging environment is : [http://134.122.95.165/](http://134.122.95.165/) and it should probably work.

**Comment by Bhupesh-mfsi** [comment]
@AlexNi245 Can you also check this please? I am not sure why this error occurs for some accounts. Please check this screenshotfile:///home/bhupesh/Pictures/Screenshots/Screenshot%20from%202023-10-03%2013-15-35.png
-9:-12:85:46
