### ISSUE TITLE
BUG: UI-Test (II)

### ISSUE THREAD

**Issue by steffenkux** [corpus-io/dm3#634]
- [x] New Profile, first login -> configure profile -> wallet address (first line) is not shown (see (A))
- [ ] Claim dm3 name works only the first time, then, claiming any name will fail (see (B))
- [x] When entering the name (dm3 name), pressing ENTER must click the button
- [ ] validity check should be performed while input (not only after pushing the claim button. (Performance issue?)
- [x] red error message above input field(dm3 name) must not move the input component
- [x] the red should be the color defined in Figma (NOT pure red #ff0000)
- [x] When switching conversations, fetching messages should not have a overlay for the full component
- [x] Conversation context menu: sometimes (mostly first times), menu vanishes when I move the mouse to menu item
- [x] Menus should be below, if enough place is available (see (C))
- [ ] address is shown, even when a dm3 name is set (see (D))
- [x] When add conversation is canceled, the menu must be closed, too.
- [x] Menu should open with animation (low prio)
- [x] The size of the component must not change when menu is opened
- [x] Edit message edits all messages (receiver still no published profile)
- [x] Delete message deletes all messages (receiver still no published profile), except a message with attachment
- [x] Line must go to the bottom always (see (E))
- [x] Seperator line in Input must be centered (see (F))
- [x] A deleted document must not have an attachment (see (G))

----------------------

(A) 
<img width="1027" alt="image" src="https://github.com/corpus-io/dm3/assets/26625404/19ac7141-7d46-4aa7-ab6a-fe1b873ae7d5">
(B)
![image](https://github.com/corpus-io/dm3/assets/26625404/0e74645c-25ad-4e8b-9e96-fe482db5d42a)
(C)
<img width="379" alt="image" src="https://github.com/corpus-io/dm3/assets/26625404/0d3eba53-a0bc-49fa-afd4-a99e94332b3b">
(D)
<img width="699" alt="image" src="https://github.com/corpus-io/dm3/assets/26625404/3752fffa-4192-4ef0-abe1-4a23d7892167">
(E)
<img width="309" alt="image" src="https://github.com/corpus-io/dm3/assets/26625404/a574d52d-c386-4b63-b626-60dcb7ae6fdd">
(F)
<img width="301" alt="image" src="https://github.com/corpus-io/dm3/assets/26625404/e548bb2f-85a2-44ee-99c3-5fc2382bf16d">
(G)
<img width="242" alt="image" src="https://github.com/corpus-io/dm3/assets/26625404/bf648792-c036-4e1c-8cbb-c5e022ea3867">

**Comment by Bhupesh-mfsi** [comment]
@hai-ko I have fixed all the UI related bugs. Three things are pending here: 
1. Claim dm3 name works only the first time ( This issue is same that I reported regarding DM3 name setting earlier ) (**Backend**)
2. address is shown, even when a dm3 name is set ( Same reason, as DM3 name is not fetched from backend even when its set )(**Backend**)
3. validity check should be performed while input ( I need a REGEX pattern for this )

**Comment by hai-ko** [comment]
**Regarding: validity check should be performed while input (not only after pushing the claim button. (Performance issue?)**
 That function could be used to check the validity:
 ```
 function validate(username) {
    return !username.includes('.') && ethers.utils.isValidName(username);
}
 ```

**Comment by Bhupesh-mfsi** [comment]
> > validity check should be performed while input (not only after pushing the claim button. (Performance issue?)
> 
> That function could be used to check the validity:
> 
> ```
> function validate(username) {
>    return (
>        username.length > 3 &&
>        !username.includes('.') &&
>        ethers.utils.isValidName(username)
>    );
> }
> ```

@hai-ko As per the above function the name cannot include "." But the ENS name could be like this "abcd.test.eth", so this is valid ENS name and here this logic won't work right?

**Comment by hai-ko** [comment]
> @hai-ko As per the above function the name cannot include "." But the ENS name could be like this "abcd.test.eth", so this is valid ENS name and here this logic won't work right?

This function is only for checking the user input in the claim text field. I want users only to claim one level lower than our `user.dm3.eth` suffix e.g. `alice.user.dm3.eth` and not `bob.alice.user.dm3.eth`. For all other places where an ENS name is used `ethers.utils.isValidName()` can directly be used

**Comment by hai-ko** [comment]
For add conversation `ethers.utils.isValidName()` can be used

**Comment by Bhupesh-mfsi** [comment]
Perfect, thanks for the explaination
