### ISSUE TITLE
BUG: UI-Testing 3

### ISSUE THREAD

**Issue by steffenkux** [corpus-io/dm3#639]
- [x] Login: If wallet is connected, the rainbowwallet screen must not be shown but only the signature requested (as common in any other dApp). At the moment every time I have to select metamask first. --> needed behavior: if no wallet is connected -> rainbowwallet screen to connect wallet (like MM or WC) and then asked for signature. if wallet is connected already, only ask for the signature. We might have to add the wallet info in the app (also with the possibility to disconnect)
I added an Idea in Figma: https://www.figma.com/file/SqAsFElnxNzP69pic9RQah/dm3-embedded?type=design&node-id=850-56&mode=design&t=yh3LddJfl6nuKNF7-0
- [x] Wallet change: now a popup window occurs which needs to be accepted. This user interaction is not necessary. This popup should be visible for a short time but vanish without user interaction. -> Goal: no not necessary interactions
- [x] adding stkux.eth fails (says wrong ens name in red)
- [x] adding hai-ko.eth fails, too. Ens name is accepted, but then it is adding the contact but freezes. (there is an error in the console: Uncaught (in promise) Error: missing response (requestBody=null, requestMethod="GET", serverError={}, url="http://localhost:3000/0xd47dc13e886db45fd80b0a399afe463a7df28c2a/0x9061b92300000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000c066861692d6b6f0365746800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000243b3b57de5032a86277106ae9d0263b903e9d095662725a8d6fc4b687adb2d4dc5873220b00000000000000000000000000000000000000000000000000000000.json", code=SERVER_ERROR, version=web/5.7.1)
    at f.makeError (index.ts:269:28)
    at f.throwError (index.ts:281:20)
    at index.ts:292:28
    at Generator.throw (<anonymous>)
    at s (browser-geturl.ts:55:1))

- [x] after sign-in, fetching contacts occurs, but nothing happens. In the console, an error message shows:
<img width="790" alt="image" src="https://github.com/corpus-io/dm3/assets/26625404/ab1e6a60-5d9a-4bdc-abbe-6d61088341c4"> -> expected behavior: there must not be a frozen screen. If for whatever reason something gets stuck, we must show an appropriate error message and return to the login screen or any other meaningful position

- [x] I logged in with the wallet that owns stkux.eth (on goerli), then opened configure. stkux.eth is already written in the ENS name field and marked. That is wrong as the profile is not yet published. 
<img width="1070" alt="image" src="https://github.com/corpus-io/dm3/assets/26625404/34d66df4-ff26-41d6-ae92-5fb39553c205">

- [x] After deleting and rewriting the ens name, it says, I do not own the ens but I do (wrong): I can't publish.
- [x] Login -> error. What does this error message mean?
<img width="603" alt="image" src="https://github.com/corpus-io/dm3/assets/26625404/89a4ccf4-ca3b-436c-a304-c6c2c83594bf">

**Comment by Bhupesh-mfsi** [comment]
**Login -> error. What does this error message mean?**

@hai-ko It seems there is some error in backend while authentication. It happens with some account. I have attached the screenshot for you to debug easily. Please check it.
![Screenshot from 2023-10-27 11-24-52](https://github.com/corpus-io/dm3/assets/137804674/8bd74873-7f32-4d69-975b-5600e4e7a085)
![Screenshot from 2023-10-27 11-25-05](https://github.com/corpus-io/dm3/assets/137804674/e30e5799-ca95-4b5a-b5b2-3bb34f00fe82)
