### ISSUE TITLE
BUG: UI-Testing IV

### ISSUE THREAD

**Issue by steffenkux** [corpus-io/dm3#644]
- [ ] steffen.beta... is active, sending a message from another account -> messages are not shown
- [x] Reopen it (after refresh), connection to DM3 name is lost (steffen...) (not connected anymore), reclaim not possible
- [x] Cannot claim any dm3 name 
![image](https://github.com/corpus-io/dm3/assets/26625404/6f21913e-f33f-45e4-be0e-030372fc0732)

- [x] stkux.eth is shown as connected (because it is owned by the address, but no profile is set, Wrong! only if the profile is set it must be shown as connected
![image](https://github.com/corpus-io/dm3/assets/26625404/0c6e191b-a422-4d07-9cb8-101fd7b32063)

- [ ] If ens profile is set, the button must say remove, not rename. Remove is a transaction really removing the profile from the ens name (should be a lib function). A query is needed to explain that this is a transaction and must be costly re-set...
- [x] Add contact: when the popup opens, the focus must be in the edit field (no additional mouse click should be needed
- [x] When changing the wallet (in MM), there is a popup before it goes back to the login screen:
![image](https://github.com/corpus-io/dm3/assets/26625404/6410abe0-20c6-4139-875b-ec9a2652edf1).
As this needs an additional click, the UX is not nice. Better UX would be to directly go to the login screen and show the info like this:
<img width="436" alt="image" src="https://github.com/corpus-io/dm3/assets/26625404/e78b4c59-6266-480d-8d38-70a96355763d">

- [x] After registering a DM3 name (sender): if the receiver adds the dm3 name, a second contact is created (1. address, 2. dm3 name) and merged (correct). Shown is the address but it must be the dm3 name.
- [ ] First login sender, first login receiver: messages are not delivered (in both directions). After re-signing in it works.
- [x] The [...] button: when moving the mouse over to the button, the popup menu opens (correct), when the mouse leaves the button, the menu closes (correct), except the mouse enters the menu (correct) -> UX is complicated as only leaving the button on the button works (otherwise the menu vanishes) -> we must give a little bit more tolerance (that the user can leave the button for instance diagonal down shortly leaving the button AND the menu. Solutions: if we have a delay (e.g. 3 seconds) before it is closed or have a tolerance area above the menu ...
- [x] Reply: the focus must be on the edit field
- [x] Edit: the focus must be on the edit field and cursor at the end
- [ ] Edit of a replied message: the reply info is lost
- [x] Edit message: pressing ESC must close the edit field and discard all changes
- [ ] Select a conversation with many messages: it takes 2-3 seconds until it is scrolled down to the current position and the last message is still outside the visible area -> when selecting a conversation, it shows always the last messages immediately (list scrolled down)

- [x] After re-sign in: the configure profile box is shown again, even if a dm3 name is defined - in the configure window no dm3 name is shown. I can't reenter the same nor any other (always the info, the name is not available)

- [ ] Message with pdf (58kb) as an attachment. Is shown in its own history but not delivered to the sender.
- [x] When sending a message with an attachment (file or pircture), it scrolls not enough to show the whole message at the sender's screen (the additional space for the attachment is not used.)
![image](https://github.com/corpus-io/dm3/assets/26625404/97d8a47e-31d1-4076-b8aa-374c19efed96)

- [x] pressing enter in edit field takes 2-3 secs to execute. This feels strange. Target: immediate reaction.
- [x] delete messages look too much like real messages. Should be visualized as clearly recognizable as deleted:
![image](https://github.com/corpus-io/dm3/assets/26625404/36a7e4da-b3c1-4f10-9c30-3c17ea0cf915)

- [x] can't publish to ENS name (dude.eth / 0x5e85d8d006906aedc72bd6ee967042604f14dbe6) -> says, I'm not the owner of the name (wrong, I registered it right now!)

**Comment by Bhupesh-mfsi** [comment]
@hai-ko Please look into this issues :-
1. steffen.beta... is active, sending a message from another account -> messages are not shown  : [https://github.com/corpus-io/dm3/issues/630](https://github.com/corpus-io/dm3/issues/630)
2. Remove DM3 name in configure profile gives error 400 (**Signature invalid**)
3. Message with pdf (58kb) as an attachment. Is shown in its own history but not delivered to the sender.
4. First login sender, first login receiver: messages are not delivered (in both directions). After re-signing in it works. :  : [https://github.com/corpus-io/dm3/issues/630](https://github.com/corpus-io/dm3/issues/630)

**Comment by Bhupesh-mfsi** [comment]
@hai-ko 
You can use this PDF for testing attachment issue 
[sample.pdf](https://github.com/corpus-io/dm3/files/13217518/sample.pdf)

And screenshots for error of remove DM3 name are :- 
![Screenshot from 2023-10-31 19-01-35](https://github.com/corpus-io/dm3/assets/137804674/1e5c3d39-f25a-44c5-acc4-a8fe52414f51)
![Screenshot from 2023-10-31 19-01-42](https://github.com/corpus-io/dm3/assets/137804674/9e0b0efd-2a2d-47fb-803c-fd62dd8558c4)
![Screenshot from 2023-10-31 19-01-53](https://github.com/corpus-io/dm3/assets/137804674/a64d5200-a328-4739-adad-917a34740364)
