### ISSUE TITLE
Avatars for users in conversations

### ISSUE THREAD

**Issue by steffenkux** [corpus-io/dm3#646]
## Current behavior
A static picture is shown (the same for all contacts)

## Expected Behavior
The avatar icon is shown according to the address/name information or existing avatar:
if an avatar is set, it is used, otherwise, the address is used to generate the avatar.
we can use https://effigy.im/a/....png for this. If the result is null or invalid, the simple user icon is used as a fallback

**Comment by Bhupesh-mfsi** [comment]
Used ethereum-blockies-base64 library to generate avatars for now
