### ISSUE TITLE
Bug: UI-Testing XII

### ISSUE THREAD

**Issue by steffenkux** [corpus-io/dm3#688]
### TESTED VERSION: RC1, STAGING 2023-11-30T09:59:34 a094d47

> **PRIO1** ... critical bug, blocks usage
> **PRIO2** ... bug, but doesn't block usage
> **PRIO3** ... not nice, not critical for release

- [x] **(PRIO2)** when ENS name contains old (invalid!) profile, it is not used (correct). If I go to configure profile, the name is empty (is ok, better would be that the name is in the text field, but not activated), If I click into the edit field, the name is added automatically and I can't change anything. (WRONG -> I need to be able to set the new profile.) --> **Expected behavior:** the name is already shown (in red), an error message (we have this red text if the name is not valid already!) says, that the published profile is corrupted or not valid, the button to publish it is available -> publish overwrites the existing profile.
- [x] **(PRIO2)** Sending to an ens-name is not working -> Sending from works, receiving NOT! **Assumption:** linking from address virtual name and ens name is not working, or deployment is not working ??? (Works after relogin!)
![image](https://github.com/corpus-io/dm3/assets/26625404/c86b7654-562d-4174-982e-e8a7b3ac75aa)

- [x] **(PRIO2)** Calling the ENS-Profile (from profile page) of an ENS-Name (autradix.eth) comes to the address virtual profile --> must be landing at ENS-Profile (correct after re-login)
- [x] **(PRIO2)** Can't claim any dm3 name, if ENS name is set. (Why not?) It always says, "name is not available"

- [x] **(PRIO2)** (OLD BUG) When opening the hamburger menu, the conversation is closed (WRONG), the Menu is only overlaying, and communication stays open!

----------------

- [x]  **(PRIO1)** When I have a conversation with the addr, and add the dm3 later, both conversations are merged (correct) but the messages in the first conversation (with the addr) are not shown anymore. --> If communication with addr exists, it must be visible, too, if I add the dm3 name (or ENS name)! (notice: after relogin the old conversations are still missing) _-> same on staging_ 
- [x] **(PRIO1)** in this case, I can't send a message (write - send - nothing is shown at the sender or receiver (in the other direction it works) (notice: after re-login it works) _-> same on staging_ 
- [x] **(PRIO2)** in the case, that the ens name holds an invalid profile, in the titlebar the ens name is shown instead of the valid dm3 name (or addr) --> as own identity, always the valid name must be shown!

**Comment by Bhupesh-mfsi** [comment]
The last item was never fixed that's why it occurs. Once the existing priority items are fixed I will work on this.
